### ISSUE TITLE
Win10 App exits if rich presence is enabled but discord is not open

### ISSUE THREAD

**Issue by dx3-dx3** [oddpawsx/walltaker-go-client#16]
As simple as the title, if I set discordPresence to true in my walltaker.toml but Discord.exe is not running, the app exits.
Error message "Timed out waiting for pipe '\\.\pipe\discord-ipc-o' to come available". I assume this will also happen on mac/linux but havent tested

**Comment by dx3-dx3** [comment]
similar error on linux, "dial unit /run/user/1000/discord-ipc-o: connection refused"

**Comment by oddpawsx** [comment]
Fixed in #15 , thanks. Mind to separate bug fixes and new features into separate PRs moving forward? Thanks!
